---
#
# Playbook to orchestrate installing OCP on OSP
#

- name: Prepare OCP image files
  hosts: image-server
  remote_user: root
  vars_files:
    - vars/install.yml
  pre_tasks:
    - name: Ensure local artifact directory exists
      file:
        path: "{{artifacts_dir}}"
        state: directory
      delegate_to: localhost
  roles:
    - role: image_preparation
      when: openstack_upload_images|bool

- name: Create OpenStack resources, upload OCP images and create Bastion machine
  hosts: undercloud
  remote_user: stack
  vars_files:
    - vars/install.yml
  roles:
    - osp_create_overcloud_resources
    - role: osp_upload_images
      when: openstack_upload_images|bool
    - osp_create_bastion

- name: Install OCP on OSP
  hosts: bastion
  vars_files:
    - vars/install.yml
  gather_facts: false
  roles:
    - ocp_configure_bastion
    - ocp_pbench_storage
    - ocp_dns_install
    - ocp_on_osp_install
    - role: ocp_metering
      when: ocp_metering_install|bool

- name: Add core cluster to inventory
  hosts: undercloud
  remote_user: stack
  vars:
    ocp_core_cluster: []
  vars_files:
    - vars/install.yml
  roles:
    - role: ocp_add_fips
      when: not openshift_enable_kuryr|bool
    - ocp_get_core_cluster
    - ocp_etc_hosts

- name: Use the remaining disk space on the core cluster for Pbench
  hosts: masters infras lb cns app_nodes
  vars_files:
    - vars/install.yml
  roles:
    - ocp_pbench_storage

- name: Run post OpenShift installation tasks
  hosts: bastion
  vars_files:
    - vars/install.yml
  roles:
    - ocp_copy_kube_config
    - ocp_etc_hosts
    - ocp_dns_wildcard
    - ocp_label_nodes
    - pbench_web_server

- name: Copy the certs to the location where golang looks for
  hosts: masters
  vars_files:
    - vars/install.yml
  become: yes
  tasks:
    - name: copy the certs on masters
      copy:
        src: /etc/origin/master/ca.crt
        dest: /etc/ssl/certs/
        remote_src: true
