---
#
# Installs OpenShift Metering
#

- name: Install OpenShift Metering block_device
  block:
    - name: Add OpenShift Metering variables
      template:
        src: openshift_metering_vars.yml.j2
        dest: /home/cloud-user/inventory/group_vars/openshift_metering_vars.yml

    - name: Run OpenShift Metering install playbook
      shell: |
        set -o pipefail
        . /home/cloud-user/keystonerc
        { time ansible-playbook -vvv --user openshift -e @/home/cloud-user/inventory/group_vars/openshift_metering_vars.yml -i inventory -i /home/cloud-user/openshift-ansible/playbooks/openstack/inventory.py /home/cloud-user/openshift-ansible/playbooks/openshift-metering/config.yml 2>&1 | tee -a /home/cloud-user/scale-ci/log/openshift_metering_install.log; } 2>> /home/cloud-user/scale-ci/log/openshift_metering_install.log
  always:
    - name: Collect OpenShift Metering Install artifacts
      synchronize:
        src: /home/cloud-user/scale-ci/log/
        dest: "{{artifacts_dir}}"
        mode: pull
